// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "allstackio-20180929075908--hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d2yb2n4hqjtr29.cloudfront.net",
    "aws_cognito_identity_pool_id": "us-east-1:3d0d7a46-a2c7-416c-a962-3c60e76f58ce",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_oyfS9Fx9a",
    "aws_user_pools_web_client_id": "52aag3vhdr6ubenc4pct0km3me"
};


export default awsmobile;
